version: "3.8"

services:
  web:
    build: .
    container_name: pvd_django_app
    command: gunicorn --bind 0.0.0.0:8000 pvd.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: pvd_postgres
    restart: always
    environment:
      POSTGRES_DB: pvd_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
